### ISSUE TITLE
Aristas que apuntan en direcciones opuestas

### ISSUE THREAD

**Issue by tabitaCatalan** [tabitaCatalan/python.ForceBundle#10]
Cuando hice un análisis exploratorio de las distintas medidas de compatibilidad, noté que las aristas que apuntan en dirección opuesta se comportan muy mal, deformándose excesivamente.
![image](https://user-images.githubusercontent.com/35073597/107171317-3f71b600-69a1-11eb-80ff-5d40d919a789.png)
Pienso que esto puede estar dando problemas, así que quiero intentar bajar la compatibilidad de esas aristas a 0.

**Comment by zorzalerrante** [comment]
Que extraño comportamiento. En rigor esas aristas no debiesen influenciarse entre sí.

**Comment by tabitaCatalan** [comment]
Creo que es un caso que no consideraron en el paper. Ellos solo dijeron que las aristas perpendiculares deberían ser incompatibles, por lo que definen la medida de compatibilidad <a href="https://www.codecogs.com/eqnedit.php?latex=C_\alpha(P,Q)&space;=&space;\frac{|\cos(\alpha)|}{|P|&space;|Q|}" target="_blank"><img src="https://latex.codecogs.com/svg.latex?C_\alpha(P,Q)&space;=&space;|\cos(\alpha)|" title="C_\alpha(P,Q) = |\cos(\alpha)|" /></a>, donde <a href="https://www.codecogs.com/eqnedit.php?latex=\alpha" target="_blank"><img src="https://latex.codecogs.com/svg.latex?\alpha" title="\alpha" /></a> es el ángulo que forman las aristas entre sí. Claramente, para el caso en que las aristas son perpendiculares, la compatibilidad es 0. Ahora bien, para el caso en que las aristas apuntan en sentido opuesto se tiene que <a href="https://www.codecogs.com/eqnedit.php?latex=\alpha&space;=&space;\pi" target="_blank"><img src="https://latex.codecogs.com/svg.latex?\alpha&space;=&space;\pi" title="\alpha = \pi" /></a>, lo que da compatibilidad uno, la máxima posible.

Las aristas que apuntan en sentido opuesto, sin embargo, son bastante problemáticas, como se ve en la imagen del primer comentario. Esto es debido a que las fuerza que actúan entre dos aristas en realidad actúan entre los nodos con el _mismo número_, como se ve en la imagen.

![Aristas que apuntan en direcciones opuestas](https://user-images.githubusercontent.com/35073597/107319946-897c9980-6a7e-11eb-81ce-79dfaa9964c3.png)

Lo que yo haría es simplemente eliminar la interacción entre las aristas que apuntan en sentido opuesto. En la práctica, esto significa las aristas tales que <a href="https://www.codecogs.com/eqnedit.php?latex=\cos(\alpha)&space;<&space;0" target="_blank"><img src="https://latex.codecogs.com/svg.latex?\cos(\alpha)&space;<&space;0" title="\cos(\alpha) < 0" /></a>. Eso es sencillo, basta con considerar la medida de compatibilidad <a href="https://www.codecogs.com/eqnedit.php?latex=C_\alpha'(P,&space;Q)&space;=&space;\max(0,&space;\cos(\alpha))" target="_blank"><img src="https://latex.codecogs.com/svg.latex?C_\alpha'(P,&space;Q)&space;=&space;\max(0,&space;\cos(\alpha))" title="C_\alpha'(P, Q) = \max(0, \cos(\alpha))" /></a>.
